# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_choice_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voter_list',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
