# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_choice_voter_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voter_list',
            field=models.TextField(default=''),
        ),
    ]
